sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tSHcq5xxyCz9fc9Nbbi
    access-key-secret: CqhgIRuUy3Gj8ILn3FiRwEv5HENYO3
    bucket-name: take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxecc0f4180fb7b09e
    secret: 1d8e7b7c87ea72b81d1b5e86661d1a2c